-- 0002_lookup_tables.sql
-- Canonical registries: peptides, suppliers, supplier_products.
-- Includes the shared set_updated_at() trigger function (first use here).
-- Seed data: 3 peptides, 3 suppliers, 9 supplier_products
--   - Bachem & Sigma rows have real SKUs and product URLs (6 rows).
--   - Cayman rows are TODO sentinels (3 rows) — scraper skips them until URLs land.
-- mass_per_unit_mg is seeded as 1.0 placeholder; the scraper extracts the real
-- value from each product page on its first successful scrape.

-- Shared trigger function: bumps updated_at to now() on every UPDATE.
-- Reused by every table that has an updated_at column.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ─── peptides ───────────────────────────────────────────────────────────────
create table public.peptides (
  id            bigint generated by default as identity primary key,
  code          text not null unique,
  display_name  text not null,
  full_name     text not null,
  description   text,
  status        public.peptide_status not null default 'active',
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create trigger peptides_set_updated_at
  before update on public.peptides
  for each row execute function public.set_updated_at();

-- ─── suppliers ──────────────────────────────────────────────────────────────
create table public.suppliers (
  id              bigint generated by default as identity primary key,
  code            text not null unique,
  display_name    text not null,
  homepage_url    text not null,
  scraper_module  text not null,
  status          public.supplier_status not null default 'active',
  notes           text,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create trigger suppliers_set_updated_at
  before update on public.suppliers
  for each row execute function public.set_updated_at();

-- ─── supplier_products ──────────────────────────────────────────────────────
-- One row per (supplier, peptide, sku). is_reference_sku marks the canonical
-- SKU we treat as the supplier's representative price for that peptide.
create table public.supplier_products (
  id                bigint generated by default as identity primary key,
  supplier_id       bigint not null references public.suppliers(id) on delete restrict,
  peptide_id        bigint not null references public.peptides(id) on delete restrict,
  supplier_sku      text not null,
  product_url       text not null,
  product_name      text not null,
  mass_per_unit_mg  numeric(20, 6) not null,
  purity_grade      text,
  is_reference_sku  boolean not null default false,
  active            boolean not null default true,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  constraint supplier_products_supplier_sku_unique unique (supplier_id, supplier_sku)
);

create index supplier_products_peptide_supplier_active_idx
  on public.supplier_products (peptide_id, supplier_id)
  where active;

create index supplier_products_supplier_reference_idx
  on public.supplier_products (supplier_id)
  where is_reference_sku;

create trigger supplier_products_set_updated_at
  before update on public.supplier_products
  for each row execute function public.set_updated_at();

-- ─── seed: peptides ─────────────────────────────────────────────────────────
insert into public.peptides (code, display_name, full_name, description) values
  ('GLP1',   'GLP-1',   'Glucagon-Like Peptide 1',
   'Incretin hormone analog; class includes semaglutide, liraglutide. Reference fragment 7-36 amide.'),
  ('BPC157', 'BPC-157', 'Body Protection Compound 157',
   'Synthetic 15-amino-acid peptide derived from human gastric juice protein.'),
  ('TB500',  'TB-500',  'Thymosin Beta-4 Fragment',
   'Active fragment of thymosin β4; widely studied in tissue repair contexts.');

-- ─── seed: suppliers ────────────────────────────────────────────────────────
insert into public.suppliers (code, display_name, homepage_url, scraper_module) values
  ('BACHEM', 'Bachem AG',                    'https://www.bachem.com/',         'bachem'),
  ('SIGMA',  'Sigma-Aldrich (MilliporeSigma)','https://www.sigmaaldrich.com/',  'sigma'),
  ('CAYMAN', 'Cayman Chemical',              'https://www.caymanchem.com/',     'cayman');

-- ─── seed: supplier_products ────────────────────────────────────────────────
-- Bachem (real SKUs/URLs)
insert into public.supplier_products
  (supplier_id, peptide_id, supplier_sku, product_url, product_name, mass_per_unit_mg, is_reference_sku, active)
values
  ((select id from public.suppliers where code = 'BACHEM'),
   (select id from public.peptides  where code = 'GLP1'),
   '4030663',
   'https://shop.bachem.com/product/4030663/',
   'GLP-1 (7-36) amide (human, bovine, guinea pig, mouse, rat)',
   1.0, true, true),

  ((select id from public.suppliers where code = 'BACHEM'),
   (select id from public.peptides  where code = 'BPC157'),
   '4030660',
   'https://shop.bachem.com/product/4030660/',
   'Gastric Juice Peptide Fragment',
   1.0, true, true),

  ((select id from public.suppliers where code = 'BACHEM'),
   (select id from public.peptides  where code = 'TB500'),
   '4043020',
   'https://shop.bachem.com/product/4043020/',
   'Thymosin β₄ (human, bovine, horse, rat)',
   1.0, true, true);

-- Sigma (real SKUs/URLs)
insert into public.supplier_products
  (supplier_id, peptide_id, supplier_sku, product_url, product_name, mass_per_unit_mg, is_reference_sku, active)
values
  ((select id from public.suppliers where code = 'SIGMA'),
   (select id from public.peptides  where code = 'GLP1'),
   'G9416',
   'https://www.sigmaaldrich.com/US/en/product/sigma/g9416',
   'Glucagon-Like Peptide 1 Fragment 7-37 human',
   1.0, true, true),

  ((select id from public.suppliers where code = 'SIGMA'),
   (select id from public.peptides  where code = 'BPC157'),
   'SML1719',
   'https://www.sigmaaldrich.com/US/en/product/sigma/sml1719',
   'BPC 157 trifluoroacetate salt',
   1.0, true, true),

  ((select id from public.suppliers where code = 'SIGMA'),
   (select id from public.peptides  where code = 'TB500'),
   'SRP3324',
   'https://www.sigmaaldrich.com/US/en/product/sigma/srp3324',
   'Thymosin β4 human recombinant',
   1.0, true, true);

-- Cayman (TODO sentinels — scraper detects 'TODO_' prefix and skips with a
-- logged warning to scraper_runs.error_summary; real values land before soak)
insert into public.supplier_products
  (supplier_id, peptide_id, supplier_sku, product_url, product_name, mass_per_unit_mg, is_reference_sku, active)
values
  ((select id from public.suppliers where code = 'CAYMAN'),
   (select id from public.peptides  where code = 'GLP1'),
   'TODO_CAYMAN_GLP1',
   'TODO_CAYMAN_GLP1_URL',
   'TODO',
   1.0, true, true),

  ((select id from public.suppliers where code = 'CAYMAN'),
   (select id from public.peptides  where code = 'BPC157'),
   'TODO_CAYMAN_BPC157',
   'TODO_CAYMAN_BPC157_URL',
   'TODO',
   1.0, true, true),

  ((select id from public.suppliers where code = 'CAYMAN'),
   (select id from public.peptides  where code = 'TB500'),
   'TODO_CAYMAN_TB500',
   'TODO_CAYMAN_TB500_URL',
   'TODO',
   1.0, true, true);
