-- 0003_users_and_points.sql
-- User identity (mirroring Supabase auth.users) and the points ledger system.
--
-- Invariants enforced here:
--   - One row in public.users per row in auth.users (created by trigger).
--   - point_ledger is APPEND-ONLY (no UPDATE/DELETE policies; not enforced
--     at the table level — relies on backend never issuing UPDATE/DELETE).
--   - Per-user idempotency via unique (user_id, idempotency_key); nullable so
--     internal entries without a key are allowed (multiple NULLs OK).
--   - point_balances is a denormalized cache. Backend ledger code uses
--     SELECT ... FOR UPDATE inside a SERIALIZABLE transaction to mutate it.
--   - point_grants has a partial unique index for grant_kind='signup' so each
--     user can receive exactly one signup grant.
--
-- The handle_new_auth_user() trigger atomically creates all four rows
-- (users, point_balances, point_grants, point_ledger) for the 10,000-point
-- signup grant inside a single auth.users INSERT.

-- ─── users ──────────────────────────────────────────────────────────────────
-- Mirrors auth.users 1:1 via the trigger below. id matches auth.users.id.
create table public.users (
  id              uuid primary key default gen_random_uuid(),
  email           text unique,
  wallet_pubkey   text unique,
  display_name    text,
  referred_by     uuid references public.users(id) on delete set null,
  referral_code   text unique,
  created_at      timestamptz not null default now(),
  last_login_at   timestamptz,
  status          text not null default 'active',
  is_admin        boolean not null default false
);

-- ─── point_ledger ───────────────────────────────────────────────────────────
-- Append-only log. amount can be negative. idempotency_key is per-user-unique
-- when set; the worker prunes idempotency_key (sets it to null) for entries
-- older than 90 days, which preserves the ledger row but releases the unique
-- slot for reuse by a different op.
create table public.point_ledger (
  id               bigint generated by default as identity primary key,
  user_id          uuid not null references public.users(id) on delete restrict,
  amount           numeric(20, 6) not null,
  reason           text not null,
  reference_kind   text,
  reference_id     bigint,
  idempotency_key  text,
  created_at       timestamptz not null default now(),
  constraint point_ledger_user_idem_unique unique (user_id, idempotency_key)
);

create index point_ledger_user_created_idx
  on public.point_ledger (user_id, created_at desc);

create index point_ledger_reason_created_idx
  on public.point_ledger (reason, created_at desc);

-- ─── point_balances ─────────────────────────────────────────────────────────
-- Cached per-user balance. Mutated only inside SERIALIZABLE txns by backend
-- ledger code, with SELECT ... FOR UPDATE on the row before increment.
create table public.point_balances (
  user_id          uuid primary key references public.users(id) on delete restrict,
  balance          numeric(20, 6) not null default 0,
  last_updated_at  timestamptz not null default now()
);

-- ─── point_grants ───────────────────────────────────────────────────────────
-- Records of grant *issuance* (separate from the ledger, which records
-- *movement*). One grant typically produces one ledger row.
create table public.point_grants (
  id                bigint generated by default as identity primary key,
  user_id           uuid not null references public.users(id) on delete restrict,
  grant_kind        text not null,
  amount            numeric(20, 6) not null,
  granted_for_date  date,
  created_at        timestamptz not null default now(),
  constraint point_grants_kind_date_unique unique (user_id, grant_kind, granted_for_date)
);

-- A regular unique on (user_id, grant_kind, granted_for_date) does not prevent
-- duplicate signup grants because granted_for_date is null for signup, and
-- Postgres treats NULL != NULL in unique constraints. This partial index
-- enforces "exactly one signup grant per user".
create unique index point_grants_signup_unique
  on public.point_grants (user_id)
  where grant_kind = 'signup';

-- ─── auth bridge: handle_new_auth_user ──────────────────────────────────────
-- Fires AFTER INSERT on auth.users. Atomically creates the user's public row,
-- their balance cache (seeded to 10,000), the signup grant record, and the
-- corresponding ledger entry — all inside the auth.users INSERT transaction.
--
-- SECURITY DEFINER + search_path pin: function executes with the privileges
-- of its owner (postgres in Supabase, which bypasses RLS) and cannot be
-- subverted by search_path manipulation.
create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_signup_grant   numeric(20, 6) := 10000;
  v_referral_code  text;
  v_grant_id       bigint;
  v_attempts       int := 0;
begin
  -- Generate a unique 8-char referral code (retry on collision, give up after 5).
  loop
    v_referral_code := upper(substring(replace(gen_random_uuid()::text, '-', ''), 1, 8));
    exit when not exists (select 1 from public.users where referral_code = v_referral_code);
    v_attempts := v_attempts + 1;
    if v_attempts > 5 then
      v_referral_code := null;
      exit;
    end if;
  end loop;

  -- 1. Mirror auth.users → public.users.
  insert into public.users (id, email, referral_code)
  values (new.id, new.email, v_referral_code);

  -- 2. Initialize the balance cache with the signup grant.
  insert into public.point_balances (user_id, balance, last_updated_at)
  values (new.id, v_signup_grant, now());

  -- 3. Record the grant issuance.
  insert into public.point_grants (user_id, grant_kind, amount, granted_for_date)
  values (new.id, 'signup', v_signup_grant, null)
  returning id into v_grant_id;

  -- 4. Append the ledger entry. idempotency_key='signup' guarantees one-per-user.
  insert into public.point_ledger
    (user_id, amount, reason, reference_kind, reference_id, idempotency_key)
  values
    (new.id, v_signup_grant, 'signup_grant', 'point_grants', v_grant_id, 'signup');

  return new;
end;
$$;

-- Drop first in case it already exists from a prior partial migration.
drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_auth_user();
