-- 0004_scraper_pipeline.sql
-- Time-series ingestion pipeline.
--
-- Data flow each minute:
--   scraper opens a scraper_runs row, hits each active supplier_product,
--   writes one supplier_observations row per attempt (success or failure),
--   detects availability_tier transitions (writes availability_events),
--   then closes the run row.
--
--   Worker reads the rolling 5-minute window of observations, computes a
--   per-supplier TWAP (supplier_twaps), drops cross-supplier outliers
--   (logs to outlier_log), and writes the blended peptide_twaps row.
--
-- Idempotency:
--   - supplier_twaps unique (peptide_id, supplier_id, computed_at)
--   - peptide_twaps  unique (peptide_id, computed_at)
--   Worker uses ON CONFLICT DO NOTHING so re-runs in the same minute are no-ops.

-- ─── scraper_runs ───────────────────────────────────────────────────────────
-- One row per scraper cycle. Status transitions: 'running' → 'success' |
-- 'partial' | 'failed'. Counters are incremented as products complete.
create table public.scraper_runs (
  id                    bigint generated by default as identity primary key,
  started_at            timestamptz not null default now(),
  finished_at           timestamptz,
  status                text not null default 'running',
  products_attempted    integer not null default 0,
  products_succeeded    integer not null default 0,
  products_failed       integer not null default 0,
  error_summary         text,
  host                  text,
  git_sha               text
);

create index scraper_runs_started_idx
  on public.scraper_runs (started_at desc);

-- ─── supplier_observations ──────────────────────────────────────────────────
-- Raw scrape results. Always inserted (success or failure) so we can audit
-- coverage. raw_html_hash enables change detection between scrapes.
create table public.supplier_observations (
  id                   bigint generated by default as identity primary key,
  supplier_product_id  bigint not null references public.supplier_products(id) on delete restrict,
  peptide_id           bigint not null references public.peptides(id) on delete restrict,
  supplier_id          bigint not null references public.suppliers(id) on delete restrict,
  observed_at          timestamptz not null,
  scraper_run_id       bigint not null references public.scraper_runs(id) on delete restrict,
  raw_price            numeric(20, 6),
  raw_currency         text,
  fx_rate_to_usd       numeric(20, 8),
  price_usd_per_mg     numeric(20, 6),
  raw_availability     text,
  availability_tier    public.availability_tier not null default 'unknown',
  lead_time_days       integer,
  scrape_success       boolean not null,
  scrape_error         text,
  http_status          integer,
  raw_html_hash        text,
  created_at           timestamptz not null default now()
);

create index supplier_observations_peptide_observed_idx
  on public.supplier_observations (peptide_id, observed_at desc);

create index supplier_observations_product_observed_idx
  on public.supplier_observations (supplier_product_id, observed_at desc);

-- Partial index lets us efficiently page through failures per supplier without
-- scanning the (much larger) successful-observation set.
create index supplier_observations_supplier_failures_idx
  on public.supplier_observations (supplier_id, observed_at desc)
  where scrape_success = false;

-- ─── supplier_twaps ─────────────────────────────────────────────────────────
-- Per-supplier 5-minute TWAP, recomputed every minute.
-- sample_count is total observations in the window; sample_count_used excludes
-- failed scrapes / null prices.
create table public.supplier_twaps (
  id                  bigint generated by default as identity primary key,
  peptide_id          bigint not null references public.peptides(id) on delete restrict,
  supplier_id         bigint not null references public.suppliers(id) on delete restrict,
  computed_at         timestamptz not null,
  window_start        timestamptz not null,
  window_end          timestamptz not null,
  twap_usd_per_mg     numeric(20, 6) not null,
  sample_count        integer not null,
  sample_count_used   integer not null,
  created_at          timestamptz not null default now(),
  constraint supplier_twaps_unique unique (peptide_id, supplier_id, computed_at)
);

create index supplier_twaps_peptide_supplier_computed_idx
  on public.supplier_twaps (peptide_id, supplier_id, computed_at desc);

-- ─── peptide_twaps ──────────────────────────────────────────────────────────
-- Cross-supplier blended TWAP (median across surviving supplier_twaps after
-- outlier removal). This is what the frontend chart reads.
--
-- input_supplier_twap_ids stores the IDs we used in the median; dropped IDs
-- go in dropped_supplier_twap_ids. Both are bigint[] (no FK enforcement on
-- arrays, intentional — the supplier_twaps rows are immutable so referential
-- integrity is implicit).
create table public.peptide_twaps (
  id                          bigint generated by default as identity primary key,
  peptide_id                  bigint not null references public.peptides(id) on delete restrict,
  computed_at                 timestamptz not null,
  window_start                timestamptz not null,
  window_end                  timestamptz not null,
  twap_usd_per_mg             numeric(20, 6) not null,
  suppliers_used              integer not null,
  suppliers_dropped           integer not null default 0,
  median_deviation_bps        integer,
  input_supplier_twap_ids     bigint[] not null,
  dropped_supplier_twap_ids   bigint[] not null default '{}',
  created_at                  timestamptz not null default now(),
  constraint peptide_twaps_unique unique (peptide_id, computed_at)
);

create index peptide_twaps_peptide_computed_idx
  on public.peptide_twaps (peptide_id, computed_at desc);

-- ─── outlier_log ────────────────────────────────────────────────────────────
-- One row per dropped outlier. Either supplier_observation_id or
-- supplier_twap_id is set (depending on whether the outlier was a single
-- observation or a full supplier-TWAP).
create table public.outlier_log (
  id                       bigint generated by default as identity primary key,
  peptide_id               bigint not null references public.peptides(id) on delete restrict,
  supplier_id              bigint not null references public.suppliers(id) on delete restrict,
  supplier_observation_id  bigint references public.supplier_observations(id) on delete set null,
  supplier_twap_id         bigint references public.supplier_twaps(id) on delete set null,
  detected_at              timestamptz not null default now(),
  reason                   text not null,
  deviation_bps            integer,
  median_value             numeric(20, 6),
  observed_value           numeric(20, 6)
);

create index outlier_log_peptide_detected_idx
  on public.outlier_log (peptide_id, detected_at desc);

-- ─── availability_events ────────────────────────────────────────────────────
-- Detected by the scraper when it sees a supplier_product transition between
-- availability_tiers (e.g., in_stock → out_of_stock). The event references
-- the previous and current observation rows so we can replay the change.
create table public.availability_events (
  id                       bigint generated by default as identity primary key,
  peptide_id               bigint not null references public.peptides(id) on delete restrict,
  supplier_id              bigint not null references public.suppliers(id) on delete restrict,
  supplier_product_id      bigint not null references public.supplier_products(id) on delete restrict,
  event_type               public.event_type not null,
  detected_at              timestamptz not null default now(),
  previous_observation_id  bigint references public.supplier_observations(id) on delete set null,
  current_observation_id   bigint not null references public.supplier_observations(id) on delete restrict,
  previous_tier            public.availability_tier,
  current_tier             public.availability_tier,
  notes                    text
);

create index availability_events_peptide_detected_idx
  on public.availability_events (peptide_id, detected_at desc);

create index availability_events_type_detected_idx
  on public.availability_events (event_type, detected_at desc);
