-- 0005_amm.sql
-- Constant-product AMM pools, trade log, and per-user positions.
--
-- One pool per peptide (enforced via unique constraint on amm_pools.peptide_id).
-- Reserves use numeric(40,18) so x*y=k math doesn't compound rounding error.
-- Oracle prices are integer micro-USD (bigint) to keep oracle math exact.
--
-- All trade execution happens in backend code inside SERIALIZABLE transactions
-- with SELECT ... FOR UPDATE on the pool row. The amm_trades insert and the
-- amm_pools UPDATE happen atomically alongside the point_ledger debit/credit.
--
-- Phase A leaves these tables empty. AMM pools are seeded in Phase B once we
-- have stable peptide_twaps to bootstrap initial reserves.

-- ─── amm_pools ──────────────────────────────────────────────────────────────
-- One row per peptide. peptide_reserve is denominated in mg of peptide;
-- points_reserve is in points. The implied pool price is points_reserve /
-- peptide_reserve (points per mg).
--
-- event_fee_active_until: when set, fee_bps is overridden by the elevated
-- "event fee" (driven by an active prediction market — see event_activations).
-- last_oracle_price_micro: most recent oracle price snapshot, integer
-- micro-USD per mg. The pool deviation check rejects trades that would push
-- the pool price more than X bps from oracle.
create table public.amm_pools (
  id                         bigint generated by default as identity primary key,
  peptide_id                 bigint not null unique references public.peptides(id) on delete restrict,
  peptide_reserve            numeric(40, 18) not null,
  points_reserve             numeric(40, 18) not null,
  fee_bps                    integer not null default 30,
  event_fee_active_until     timestamptz,
  slippage_curve_kind        text not null default 'constant_product',
  last_oracle_price_micro    bigint not null,
  last_oracle_check_at       timestamptz not null,
  created_at                 timestamptz not null default now(),
  updated_at                 timestamptz not null default now(),
  constraint amm_pools_reserves_nonneg check (peptide_reserve >= 0 and points_reserve >= 0),
  constraint amm_pools_fee_bps_range check (fee_bps >= 0 and fee_bps <= 10000)
);

create trigger amm_pools_set_updated_at
  before update on public.amm_pools
  for each row execute function public.set_updated_at();

-- ─── amm_trades ─────────────────────────────────────────────────────────────
-- Append-only trade log. Exactly one of (points_in/peptide_out) or
-- (peptide_in/points_out) is populated per row, determined by direction.
-- pool_price_after is the implied price right after this trade settles.
create table public.amm_trades (
  id                            bigint generated by default as identity primary key,
  pool_id                       bigint not null references public.amm_pools(id) on delete restrict,
  peptide_id                    bigint not null references public.peptides(id) on delete restrict,
  user_id                       uuid not null references public.users(id) on delete restrict,
  direction                     text not null,
  points_in                     numeric(40, 18),
  peptide_in                    numeric(40, 18),
  points_out                    numeric(40, 18),
  peptide_out                   numeric(40, 18),
  fee_paid_points               numeric(40, 18) not null,
  oracle_price_micro_at_trade   bigint not null,
  pool_price_after              numeric(40, 18) not null,
  created_at                    timestamptz not null default now(),
  constraint amm_trades_direction_check check (direction in ('buy_peptide', 'sell_peptide')),
  constraint amm_trades_buy_legs check (
    direction <> 'buy_peptide' or (points_in is not null and peptide_out is not null)
  ),
  constraint amm_trades_sell_legs check (
    direction <> 'sell_peptide' or (peptide_in is not null and points_out is not null)
  )
);

create index amm_trades_user_created_idx
  on public.amm_trades (user_id, created_at desc);

create index amm_trades_peptide_created_idx
  on public.amm_trades (peptide_id, created_at desc);

create index amm_trades_pool_created_idx
  on public.amm_trades (pool_id, created_at desc);

-- ─── positions ──────────────────────────────────────────────────────────────
-- Per-user net peptide holdings, with running average entry price (micro-USD
-- per mg) for unrealized PnL display. amount can go to 0 (fully closed) but
-- the row persists for historical lookup.
create table public.positions (
  user_id                uuid not null references public.users(id) on delete restrict,
  peptide_id             bigint not null references public.peptides(id) on delete restrict,
  amount                 numeric(40, 18) not null,
  avg_entry_price_micro  bigint not null,
  updated_at             timestamptz not null default now(),
  primary key (user_id, peptide_id),
  constraint positions_amount_nonneg check (amount >= 0)
);

create trigger positions_set_updated_at
  before update on public.positions
  for each row execute function public.set_updated_at();
