-- 0007_event_bridge_and_treasury.sql
-- The bridge between prediction markets and AMM pools, plus the global
-- treasury singleton and pre-computed leaderboard snapshots.
--
-- event_activations records the moment a prediction market becomes "active"
-- enough to elevate the AMM pool's fee tier and accelerate the oracle TWAP
-- update cadence for the linked peptide. The worker writes these rows when
-- a market transitions to a high-volume state and reads them on every tick
-- to decide which pools should run hot.

-- ─── event_activations ──────────────────────────────────────────────────────
create table public.event_activations (
  id                                bigint generated by default as identity primary key,
  market_id                         bigint not null references public.prediction_markets(id) on delete restrict,
  amm_pool_id                       bigint not null references public.amm_pools(id) on delete restrict,
  peptide_id                        bigint not null references public.peptides(id) on delete restrict,
  activated_at                      timestamptz not null default now(),
  expires_at                        timestamptz not null,
  fee_tier_during_activation_bps    integer not null,
  oracle_accelerated_until          timestamptz not null,
  constraint event_activations_fee_range
    check (fee_tier_during_activation_bps >= 0 and fee_tier_during_activation_bps <= 10000),
  constraint event_activations_window_valid
    check (expires_at > activated_at)
);

create index event_activations_peptide_activated_idx
  on public.event_activations (peptide_id, activated_at desc);

-- ─── treasury ───────────────────────────────────────────────────────────────
-- Singleton row tracking total points collected by the house (AMM fees,
-- prediction market fees, etc.). Mutated under the same SERIALIZABLE +
-- SELECT FOR UPDATE pattern as point_balances.
create table public.treasury (
  id                       bigint primary key default 1,
  total_points_collected   numeric(40, 18) not null default 0,
  last_updated_at          timestamptz not null default now(),
  constraint treasury_singleton check (id = 1)
);

insert into public.treasury (id, total_points_collected, last_updated_at)
values (1, 0, now());

-- ─── leaderboard_snapshots ──────────────────────────────────────────────────
-- Pre-computed leaderboards. The worker writes a fresh snapshot per period
-- on its cron schedule; the frontend reads only the latest snapshot per
-- period. rankings is an ordered jsonb array of {user_id, display_name,
-- points, rank} objects.
create table public.leaderboard_snapshots (
  id           bigint generated by default as identity primary key,
  snapshot_at  timestamptz not null default now(),
  period       text not null,
  rankings     jsonb not null,
  constraint leaderboard_snapshots_period_check
    check (period in ('all_time', 'season', 'weekly'))
);

create index leaderboard_snapshots_period_snapshot_idx
  on public.leaderboard_snapshots (period, snapshot_at desc);
